### ISSUE TITLE
How to actually use this

### ISSUE THREAD

**Issue by kurellajunior** [http4s/http4s-prometheus-metrics#88]
Hey, for someone with only limited knowledge around all this Resource/F things it would be extremely helpful to get a simple example in the Readme.md on how to actually use it, i.e. how to combine the PrometheusExportService with an existing http4s App…

**Comment by martinprobson** [comment]
Hi @kurellajunior ,
Please see this link https://github.com/http4s/http4s-prometheus-metrics/issues/145#issuecomment-2065315565 I hope it helps a bit....

**Comment by kurellajunior** [comment]
Hi @martinprobson,
That is amazing work you did there. Unfortunately, we meanwhile moved away from http4s to Play. Which is slower but way easier to understand. (No metrics there yet too).
But you work will surely be helpful to others
